### ISSUE TITLE
Maybe there is one typo error

### ISSUE THREAD

**Issue by andy74911** [IntergatedCircuits/HidSharp#13]
HidSharp/Reports/ReportDescriptor.cs 
seams there is one typo 
@ Line170
I think currect one seams 
State.GlobalItemStateStack.RemoveAt(State.GlobalItemStateStack.Count - 1);

Please check it, thanks.

**Comment by benedekkupper** [comment]
Hi! Thanks for your report. Please try to use github's functionality to link to a specific line of code, e.g. like this: https://github.com/IntergatedCircuits/HidSharp/blob/e8359220e0cdb1541844835055f5f19af02a9f4c/HidSharp/Reports/ReportDescriptor.cs#L170

So what is in your opinion wrong in this line, and what is your assumption about the correction for it?

**Comment by andy74911** [comment]
Thanks for your advice.
I think correct one is 
State.GlobalItemStateStack.RemoveAt(State.GlobalItemStateStack.Count - 1);

**Comment by benedekkupper** [comment]
@andy74911 Please verify that my new commit c6e9365 solves the problem.

**Comment by andy74911** [comment]
I had tried it and original fail case is working now. Thanks.
By the way,can I ask  when will it publish this version on NuGet.

**Comment by benedekkupper** [comment]
Thanks for the verification!
Unfortunately this repo is a fork of the original library, and I have no contact with the original author (who owns the nuget package), so I cannot give you any ETA for this fix.
