### ISSUE TITLE
Get list of only USB scales?

### ISSUE THREAD

**Issue by StephenLKearney** [IntergatedCircuits/HidSharp#16]
Is there a way to filter the list of devices to only USB scales?  Currently I'm only selecting the devices with a Manufacturer value that matches my hard-coded list (e.g. "DYMO") but I'd like something more flexible so that I won't have to update my list when there's a new scale manufacturer.  I see the Usage enums but I'm not clear on how to use them.  TIA.

**Comment by benedekkupper** [comment]
This is why I added commit c91f5e2e, you can use that API to find devices based on top level usage.
