### ISSUE TITLE
How To Use Guide

### ISSUE THREAD

**Issue by yldzmuhammed** [IntergatedCircuits/HidSharp#3]
Hello to everyone,

First of all thanks for this great job.

And secondly, i don't know how to use this library. Especially starting the connection.

In my application program, i want to keep tracking the connection status and update device status on the (device plugged and unplugged) form.

**Comment by benedekkupper** [comment]
You can start by running HidSharp.Test. There's available documentation here: https://docs.zer7.com/hidsharp/

**Comment by yldzmuhammed** [comment]
Thank you for your response. But i do not see any kindof starting guide or something like that. Is there any?
I am asking because some people not suggests not to use the read/write. Instead GetFeature, SetFeature.
So can you make a guide for it?

**Comment by benedekkupper** [comment]
Do you want a guide for this library, or writing HID device applications on an MCU? The former is available on the above link, and the latter is out of scope here.

The HID device defines its reports, including which type they are. So this library has to adapt to whatever device it interfaces with. For the record I've used this library to transfer all report types (IN, OUT, FEATURE) without problem.
